package io.github.flavyu22.movietorrentsearchtv.model

import androidx.compose.runtime.Immutable

// ─── Model complet pentru toate stringurile UI ─────────────────────────────────
// Nicio resursă text hardcodată în composable-uri — totul trece prin AppStrings
@Immutable
data class AppStrings(
    // Generale
    val yes: String,
    val no: String,
    val back: String,
    val save: String,
    val refresh: String,
    val cancel: String,
    val confirm: String = "Confirm",

    // Dialogs
    val exitTitle: String,
    val exitMessage: String,
    val updateTitle: String,
    val updateMessage: String,
    val aboutTitle: String,
    val aboutText: String,
    val logoutConfirm: String,

    // Navigare / Meniu
    val movies: String,
    val series: String,
    val changeLanguage: String,
    val update: String,
    val checkingUpdates: String,
    val about: String,
    val trailer: String,
    val logout: String,
    val history: String,
    val clearHistory: String,
    val torrserverSettings: String,
    val tmdbSettings: String = "TMDB Settings",
    val scanNetwork: String,
    val movieLabel: String,
    val seriesLabel: String,
    val availableServers: String,
    val torrserverInfo: String,

    // Filtre
    val genres: String,
    val years: String,
    val quality: String,
    val rating: String,
    val sortBy: String,
    val sortSeeds: String,
    val sortSize: String,
    val sortSource: String,
    val searchPlaceholder: String,
    /** Torrent language filter chip ("only releases in the selected app language"). */
    val torrentLanguageFilter: String = "Only my language",

    // Paginare
    val prev: String,
    val next: String,
    val page: String,

    // Torrent / Playback
    val magnetSources: String,
    val otherSources: String,
    val noSources: String,
    val multiSourceResults: String,
    val processingTorrserver: String,
    val searchingMultiple: String,
    val playWith: String,
    val installBitTorrent: String,
    val installPlayer: String,
    val resultsSummary: String,
    val torrserverConnected: String,

    // Auth
    val loginTitle: String,
    val username: String,
    val password: String,
    val login: String,
    val loginError: String,
    val loginEmptyFields: String,
    val contactCredentials: String,

    // Erori
    val playerError: String,
    val torrserverError: String,

    // Misc
    val voiceLang: String,
    val langName: String,
    val developer: String,

    // Local security / external intents. Defaults keep existing translations
    // source-compatible until dedicated localized copy is added.
    val authSetupTitle: String = "Create local access",
    val authSetupMessage: String = "Create a local profile and PIN or passphrase. It never leaves this device.",
    val authUnlockMessage: String = "Unlock the local profile on this device.",
    val authSetupAction: String = "Create and continue",
    val authLockedMessage: String = "Too many attempts. Try again in %d seconds.",
    val authCredentialHint: String = "Use at least 6 characters.",
    val authConfirmCredential: String = "Confirm PIN or passphrase",
    val authCredentialMismatch: String = "The credentials do not match.",
    val authResetAction: String = "Reset local access",
    val authResetConfirm: String = "The local credential data is damaged. Reset it and create a new credential?",
    val magnetConfirmTitle: String = "Open magnet link?",
    val magnetConfirmMessage: String = "Another app requested torrent playback. Continue only if you trust the source.",

    // Android TV state, accessibility and external-app feedback.
    val retry: String = "Retry",
    val allFilter: String = "All",
    val loading: String = "Loading…",
    val genericMovie: String = "Movie",
    val close: String = "Close",
    val menu: String = "Menu",
    val voiceSearch: String = "Voice search",
    val actionUnavailableTitle: String = "Action unavailable",
    val voiceSearchUnavailable: String = "Voice search is not available on this device.",
    val trailerUnavailable: String = "No compatible app can open this trailer.",
    val openSourcePage: String = "Open source page",
    val playTorrent: String = "Play torrent",
    val browserContentDescription: String = "Source web page. Use the D-pad to move the pointer and press Select to activate a link.",
    val configuredServer: String = "Configured server",
    val disableTorrserver: String = "Disable Torrserver",
    val scanning: String = "Scanning…",
    val manualAddressHint: String = "192.168.1.10:8090 or https://server.example",
    val noServersFound: String = "No server found. Select “Scan network” to search again.",
    val selected: String = "Selected",
    val connectionSucceeded: String = "Connected to %s (%d ms)",
    val connectionFailed: String = "Could not connect to %s.",
    val invalidServerAddress: String = "Enter a valid Torrserver address.",
    val serverScanFailed: String = "The network scan failed. Try again.",
    val serverUnreachable: String = "The Torrserver is unreachable.",
    val catalogueNetworkIssue: String = "The catalogue could not be loaded. Check the network connection and try again.",
    val tmdbNotConfigured: String = "TMDB is not configured. The series catalogue shows recent releases from the torrent providers, without posters or ratings.",
    val partialResults: String = "Some catalogue sources are unavailable. The available results are shown.",
    val updateOperationFailed: String = "The update operation failed. Try again later.",
    val torrentResultDescription: String = "%s, %s, %s, %d seeds",
    val clearPreferredPlayer: String = "Clear preferred player",
    val myList: String = "My List",
    val clearMyList: String = "Clear My List",
    val addToMyList: String = "Add to My List",
    val removeFromMyList: String = "Remove from My List",
    val myListEmpty: String = "My List is empty.",
    val recentSearches: String = "Recent searches",
    val clearSearchHistory: String = "Clear search history",
    val copyMagnetLink: String = "Copy magnet link",
    val magnetLinkCopied: String = "Magnet link copied",
    val sortQuality: String = "Quality",
    val sortDate: String = "Date",
    /** Leechers count, shown next to the seeders on every magnet row. */
    val peers: String = "Peers",
    /** Content description of the release upload-date chip. */
    val uploadedOn: String = "Uploaded on",
    /**
     * Spoken description of a magnet row. Positional placeholders are required here because
     * the arguments mix [String] and [Int], which a repeated untyped placeholder cannot.
     */
    val torrentRowDescription: String = "%1\$s. Quality %2\$s. %3\$s. %4\$d seeds. %5\$d peers.",
    /** Empty state shown when the quality/language filters exclude every result. */
    val noResultsForFilter: String = "No results match the active filters.",
)

// ─── Traduceri ─────────────────────────────────────────────────────────────────
/**
 * Keeps only the active language materialized during startup. Opening the language
 * picker still resolves every entry, while ordinary map lookups instantiate one.
 */
private class LazyTranslationMap(
    private val translations: Map<String, Lazy<AppStrings>>,
) : AbstractMap<String, AppStrings>() {
    override val size: Int
        get() = translations.size

    override val entries: Set<Map.Entry<String, AppStrings>> by lazy {
        translations.mapTo(LinkedHashSet(translations.size)) { (language, strings) ->
            LazyTranslationEntry(language, strings)
        }
    }

    override fun containsKey(key: String): Boolean = translations.containsKey(key)

    override fun get(key: String): AppStrings? = translations[key]?.value

    private class LazyTranslationEntry(
        override val key: String,
        private val strings: Lazy<AppStrings>,
    ) : Map.Entry<String, AppStrings> {
        override val value: AppStrings
            get() = strings.value

        override fun equals(other: Any?): Boolean =
            other is Map.Entry<*, *> && key == other.key && value == other.value

        override fun hashCode(): Int = key.hashCode() xor value.hashCode()
    }
}

val Translations: Map<String, AppStrings> = LazyTranslationMap(mapOf(

    "RO" to lazy { AppStrings(
        yes = "Da", no = "Nu", back = "Înapoi", save = "Salvează",
        refresh = "Reîncarcă", cancel = "Anulează", confirm = "Confirmă",

        exitTitle = "Ieșire?", exitMessage = "Vrei să închizi aplicația?",
        updateTitle = "Update Disponibil",
        updateMessage = "O versiune nouă este disponibilă. Vrei să o descarci?",
        aboutTitle = "Despre Aplicație",
        aboutText = "MovieTorrentSearchTV v${io.github.flavyu22.movietorrentsearchtv.util.Constants.APP_VERSION}\nCăutare Filme și Seriale.\nOptimizat special pentru Android TV.",
        logoutConfirm = "Ești sigur că vrei să te deconectezi?",

        movies = "Filme", series = "Seriale",
        changeLanguage = "Schimbă Limba", update = "Update",
        checkingUpdates = "Căutare actualizări...", about = "Despre",
        trailer = "Trailer",
        logout = "Deconectare",
        history = "Istorie",
        clearHistory = "Șterge Istoria",
        torrserverSettings = "Configurare Torrserver",
        tmdbSettings = "Configurare TMDB",
        scanNetwork = "Căutare în rețea",
        movieLabel = "FILM",
        seriesLabel = "SERIAL",
        availableServers = "Servere disponibile (%d):",
        torrserverInfo = "Torrserver poate fi local (127.0.0.1:8090) sau un server online.",

        genres = "GENURI", years = "ANI", quality = "CALITATE", rating = "RATING",
        sortBy = "SORTEAZĂ", sortSeeds = "Semințe", sortSize = "Mărime", sortSource = "Sursă",
        searchPlaceholder = "Caută...",

        prev = "Prev.", next = "Urm.", page = "Pagina",

        magnetSources = "Surse Magnet:", 
        otherSources = "Alte Surse (Web):",
        noSources = "Nicio sursă găsită.",
        multiSourceResults = "▼ Rezultate Multi-Sursă",
        processingTorrserver = "Se procesează în Torrserver...",
        searchingMultiple = "Căutare în multiple surse...",
        playWith = "Alege playerul:",
        installBitTorrent = "Instalează un client BitTorrent (ex: nPlayer).",
        installPlayer = "Nicio aplicație video găsită. Instalează VLC, MX Player, Nova sau nPlayer.",
        resultsSummary = "%d rezultate (%dms)",
        torrserverConnected = "Torrserver: %s",

        loginTitle = "Autentificare", username = "Utilizator",
        password = "Parolă", login = "Intră",
        loginError = "Utilizator sau parolă incorecte!",
        loginEmptyFields = "Completează toate câmpurile",
        contactCredentials = "Acces local protejat pe acest dispozitiv",

        playerError = "Eroare player: %s",
        torrserverError = "Torrserver: %s",

        voiceLang = "ro-RO", langName = "Română",
    torrentLanguageFilter = "Doar limba mea",
        developer = "Dezvoltator: OxigenForFlower",
        authSetupTitle = "Configurează accesul local",
        authSetupMessage = "Creează un profil local și un PIN sau o frază secretă. Datele nu părăsesc dispozitivul.",
        authUnlockMessage = "Deblochează profilul local de pe acest dispozitiv.",
        authSetupAction = "Confirmă și continuă",
        authLockedMessage = "Prea multe încercări. Reîncearcă în %d secunde.",
        authCredentialHint = "Folosește cel puțin 6 caractere.",
        authConfirmCredential = "Confirmă PIN-ul sau fraza secretă",
        authCredentialMismatch = "Datele de acces nu coincid.",
        authResetAction = "Resetează accesul local",
        authResetConfirm = "Datele locale de acces sunt deteriorate. Le resetezi și creezi alte date de acces?",
        magnetConfirmTitle = "Deschizi linkul magnet?",
        magnetConfirmMessage = "Altă aplicație a solicitat redarea unui torrent. Continuă doar dacă ai încredere în sursă.",
        retry = "Reîncearcă", allFilter = "Toate", loading = "Se încarcă…", genericMovie = "Film", close = "Închide",
        menu = "Meniu", voiceSearch = "Căutare vocală",
        actionUnavailableTitle = "Acțiune indisponibilă",
        voiceSearchUnavailable = "Căutarea vocală nu este disponibilă pe acest dispozitiv.",
        trailerUnavailable = "Nicio aplicație compatibilă nu poate deschide trailerul.",
        openSourcePage = "Deschide pagina sursei", playTorrent = "Redă torrentul",
        browserContentDescription = "Pagina web a sursei. Mută indicatorul cu D-pad-ul și apasă Selectare pentru a activa un link.",
        configuredServer = "Server configurat", disableTorrserver = "Dezactivează Torrserver", scanning = "Se caută…",
        manualAddressHint = "192.168.1.10:8090 sau https://server.exemplu",
        noServersFound = "Nu s-a găsit niciun server. Selectează „Căutare în rețea” pentru a încerca din nou.",
        selected = "Selectat", connectionSucceeded = "Conectat la %s (%d ms)",
        connectionFailed = "Conectarea la %s a eșuat.",
        invalidServerAddress = "Introdu o adresă Torrserver validă.",
        serverScanFailed = "Scanarea rețelei a eșuat. Încearcă din nou.",
        serverUnreachable = "Torrserver nu poate fi contactat.",
        catalogueNetworkIssue = "Catalogul nu a putut fi încărcat. Verifică rețeaua și încearcă din nou.",
        tmdbNotConfigured = "TMDB nu este configurat. Catalogul de seriale afișează apariții recente de la furnizorii de torente, fără postere sau note.",
        partialResults = "Unele surse de catalog nu sunt disponibile. Sunt afișate rezultatele accesibile.",
        updateOperationFailed = "Operația de actualizare a eșuat. Încearcă din nou mai târziu.",
        torrentResultDescription = "%s, %s, %s, %d seed-uri",
        clearPreferredPlayer = "Șterge playerul preferat",
        myList = "Lista mea", clearMyList = "Șterge Lista mea",
        addToMyList = "Adaugă în Lista mea", removeFromMyList = "Elimină din Lista mea",
        myListEmpty = "Lista mea este goală.",
        recentSearches = "Căutări recente", clearSearchHistory = "Șterge căutările",
        copyMagnetLink = "Copiază linkul magnet", magnetLinkCopied = "Link magnet copiat",
        sortQuality = "Calitate", sortDate = "Dată",
        peers = "Leechers", uploadedOn = "Adăugat",
        torrentRowDescription = "%1\$s. Calitate %2\$s. %3\$s. %4\$d seed-uri. %5\$d leechers.",
        noResultsForFilter = "Niciun rezultat nu corespunde filtrelor active.",
    ) },

    "EN" to lazy { AppStrings(
        yes = "Yes", no = "No", back = "Back", save = "Save",
        refresh = "Refresh", cancel = "Cancel", confirm = "Confirm",

        exitTitle = "Exit?", exitMessage = "Do you want to close the app?",
        updateTitle = "Update Available",
        updateMessage = "A new version is available. Do you want to download it?",
        aboutTitle = "About App",
        aboutText = "MovieTorrentSearchTV v${io.github.flavyu22.movietorrentsearchtv.util.Constants.APP_VERSION}\nSearch Movies and Series.\nOptimized for Android TV.",
        logoutConfirm = "Are you sure you want to log out?",

        movies = "Movies", series = "Series",
        changeLanguage = "Change Language", update = "Update",
        checkingUpdates = "Checking for updates...", about = "About",
        trailer = "Trailer",
        logout = "Logout",
        history = "History",
        clearHistory = "Clear History",
        torrserverSettings = "Torrserver Settings",
        tmdbSettings = "TMDB Settings",
        scanNetwork = "Scan Network",
        movieLabel = "MOVIE",
        seriesLabel = "SERIES",
        availableServers = "Available servers (%d):",
        torrserverInfo = "Torrserver can be local (127.0.0.1:8090) or an online server.",

        genres = "GENRES", years = "YEARS", quality = "QUALITY", rating = "RATING",
        sortBy = "SORT BY", sortSeeds = "Seeds", sortSize = "Size", sortSource = "Source",
        searchPlaceholder = "Search...",

        prev = "Prev.", next = "Next", page = "Page",

        magnetSources = "Magnet Sources:", 
        otherSources = "Other Sources (Web):",
        noSources = "No sources found.",
        multiSourceResults = "▼ Multi-Source Results",
        processingTorrserver = "Processing in Torrserver...",
        searchingMultiple = "Searching multiple sources...",
        playWith = "Play with:",
        installBitTorrent = "Install a BitTorrent client (e.g. nPlayer).",
        installPlayer = "No video player found. Install VLC, MX Player, Nova, or nPlayer.",
        resultsSummary = "%d results (%dms)",
        torrserverConnected = "Torrserver: %s",

        loginTitle = "Login", username = "Username",
        password = "Password", login = "Sign In",
        loginError = "Invalid username or password!",
        loginEmptyFields = "Please fill in all fields",
        contactCredentials = "Local access protected on this device",

        playerError = "Player error: %s",
        torrserverError = "Torrserver: %s",

        voiceLang = "en-US", langName = "English",
    torrentLanguageFilter = "Only my language",
        developer = "Developer: OxigenForFlower",
        authSetupTitle = "Create local access",
        authSetupMessage = "Create a local profile and PIN or passphrase. It never leaves this device.",
        authUnlockMessage = "Unlock the local profile on this device.",
        authSetupAction = "Create and continue",
        authLockedMessage = "Too many attempts. Try again in %d seconds.",
        authCredentialHint = "Use at least 6 characters.",
        authConfirmCredential = "Confirm PIN or passphrase",
        authCredentialMismatch = "The credentials do not match.",
        authResetAction = "Reset local access",
        authResetConfirm = "The local credential data is damaged. Reset it and create a new credential?",
        magnetConfirmTitle = "Open magnet link?",
        magnetConfirmMessage = "Another app requested torrent playback. Continue only if you trust the source.",
        retry = "Retry", allFilter = "All", loading = "Loading…", genericMovie = "Movie", close = "Close",
        menu = "Menu", voiceSearch = "Voice search",
        actionUnavailableTitle = "Action unavailable",
        voiceSearchUnavailable = "Voice search is not available on this device.",
        trailerUnavailable = "No compatible app can open this trailer.",
        openSourcePage = "Open source page", playTorrent = "Play torrent",
        browserContentDescription = "Source web page. Use the D-pad to move the pointer and press Select to activate a link.",
        configuredServer = "Configured server", disableTorrserver = "Disable Torrserver", scanning = "Scanning…",
        manualAddressHint = "192.168.1.10:8090 or https://server.example",
        noServersFound = "No server found. Select “Scan network” to search again.",
        selected = "Selected", connectionSucceeded = "Connected to %s (%d ms)",
        connectionFailed = "Could not connect to %s.",
        invalidServerAddress = "Enter a valid Torrserver address.",
        serverScanFailed = "The network scan failed. Try again.",
        serverUnreachable = "The Torrserver is unreachable.",
        catalogueNetworkIssue = "The catalogue could not be loaded. Check the network connection and try again.",
        tmdbNotConfigured = "TMDB is not configured. The series catalogue shows recent releases from the torrent providers, without posters or ratings.",
        partialResults = "Some catalogue sources are unavailable. The available results are shown.",
        updateOperationFailed = "The update operation failed. Try again later.",
        torrentResultDescription = "%s, %s, %s, %d seeds",
        myList = "My List", clearMyList = "Clear My List",
        addToMyList = "Add to My List", removeFromMyList = "Remove from My List",
        myListEmpty = "My List is empty.",
        recentSearches = "Recent searches", clearSearchHistory = "Clear search history",
        copyMagnetLink = "Copy magnet link", magnetLinkCopied = "Magnet link copied",
        sortQuality = "Quality", sortDate = "Date",
        peers = "Leechers", uploadedOn = "Uploaded",
        torrentRowDescription = "%1\$s. Quality %2\$s. %3\$s. %4\$d seeds. %5\$d leechers.",
        noResultsForFilter = "No results match the active filters.",
    ) },

    "IT" to lazy { AppStrings(
        yes = "Sì", no = "No", back = "Indietro", save = "Salva",
        refresh = "Aggiorna", cancel = "Annulla", confirm = "Conferma",
        exitTitle = "Uscire?", exitMessage = "Vuoi chiudere l'applicazione?",
        updateTitle = "Aggiornamento Disponibile",
        updateMessage = "È disponibile una nuova versione. Vuoi scaricarla?",
        aboutTitle = "Info App",
        aboutText = "MovieTorrentSearchTV v${io.github.flavyu22.movietorrentsearchtv.util.Constants.APP_VERSION}\nCerca Film e Serie TV.\nOttimizzato per Android TV.",
        logoutConfirm = "Sei sicuro di voler uscire?",
        movies = "Film", series = "Serie TV",
        changeLanguage = "Cambia Lingua", update = "Aggiorna",
        checkingUpdates = "Controllo aggiornamenti...", about = "Informazioni",
        trailer = "Trailer",
        logout = "Logout",
        history = "Cronologia", clearHistory = "Cancella Cronologia",
        torrserverSettings = "Impostazioni Torrserver", scanNetwork = "Scansiona Rete",
        movieLabel = "FILM", seriesLabel = "SERIE",
        availableServers = "Server disponibili (%d):",
        torrserverInfo = "Torrserver può essere locale (127.0.0.1:8090) o un server online.",
        genres = "GENERI", years = "ANNI", quality = "QUALITÀ", rating = "VOTO",
        sortBy = "ORDINA", sortSeeds = "Seeds", sortSize = "Dimensione", sortSource = "Sorgente",
        searchPlaceholder = "Cerca...",
        prev = "Prec.", next = "Succ.", page = "Pagina",
        magnetSources = "Sorgenti Magnet:", 
        otherSources = "Altre Sorgenti (Web):",
        noSources = "Nessuna sorgente trovata.",
        multiSourceResults = "▼ Risultati Multi-Sorgente",
        processingTorrserver = "Elaborazione in Torrserver...",
        searchingMultiple = "Ricerca in più sorgenti...",
        playWith = "Riproduci con:",
        installBitTorrent = "Installa un client BitTorrent (es. nPlayer).",
        installPlayer = "Installa un lettore video.",
        resultsSummary = "%d risultati (%dms)",
        torrserverConnected = "Torrserver: %s",
        loginTitle = "Accesso", username = "Nome utente",
        password = "Password", login = "Accedi",
        loginError = "Nome utente o password non validi!",
        loginEmptyFields = "Si prega di compilare tutti i campi",
        contactCredentials = "Accesso locale protetto su questo dispositivo",
        playerError = "Errore player: %s", torrserverError = "Torrserver: %s",
        voiceLang = "it-IT", langName = "Italiano",
        developer = "Sviluppatore: OxigenForFlower",
        authSetupTitle = "Configura l'accesso locale",
        authSetupMessage = "Crea un profilo locale e un PIN o una passphrase. I dati non lasciano mai questo dispositivo.",
        authUnlockMessage = "Sblocca il profilo locale su questo dispositivo.",
        authSetupAction = "Crea e continua",
        authLockedMessage = "Troppi tentativi. Riprova tra %d secondi.",
        authCredentialHint = "Usa almeno 6 caratteri.",
        authConfirmCredential = "Conferma il PIN o la passphrase",
        authCredentialMismatch = "Le credenziali non coincidono.",
        authResetAction = "Reimposta l'accesso locale",
        authResetConfirm = "I dati delle credenziali locali sono danneggiati. Vuoi reimpostarli e creare una nuova credenziale?",
        magnetConfirmTitle = "Aprire il link magnet?",
        magnetConfirmMessage = "Un'altra app ha richiesto la riproduzione di un torrent. Continua solo se ritieni attendibile la fonte.",
        retry = "Riprova", allFilter = "Tutti", loading = "Caricamento…", genericMovie = "Film", close = "Chiudi",
        menu = "Menu", voiceSearch = "Ricerca vocale",
        actionUnavailableTitle = "Azione non disponibile",
        voiceSearchUnavailable = "La ricerca vocale non è disponibile su questo dispositivo.",
        trailerUnavailable = "Nessuna app compatibile può aprire il trailer.",
        openSourcePage = "Apri la pagina della fonte", playTorrent = "Riproduci torrent",
        browserContentDescription = "Pagina web della fonte. Usa il D-pad per spostare il puntatore e premi Seleziona per attivare un link.",
        configuredServer = "Server configurato", disableTorrserver = "Disattiva Torrserver", scanning = "Ricerca…",
        manualAddressHint = "192.168.1.10:8090 o https://server.example",
        noServersFound = "Nessun server trovato. Seleziona “Scansiona rete” per riprovare.",
        selected = "Selezionato", connectionSucceeded = "Connesso a %s (%d ms)",
        connectionFailed = "Impossibile connettersi a %s.",
        invalidServerAddress = "Inserisci un indirizzo Torrserver valido.",
        serverScanFailed = "La scansione della rete non è riuscita. Riprova.",
        serverUnreachable = "Il Torrserver non è raggiungibile.",
        catalogueNetworkIssue = "Impossibile caricare il catalogo. Controlla la rete e riprova.",
        tmdbNotConfigured = "TMDB non è configurato. Il catalogo delle serie mostra le uscite recenti dei provider di torrent, senza poster o valutazioni.",
        partialResults = "Alcune fonti del catalogo non sono disponibili. Sono mostrati i risultati disponibili.",
        updateOperationFailed = "L'operazione di aggiornamento non è riuscita. Riprova più tardi.",
        torrentResultDescription = "%s, %s, %s, %d seed",
        clearPreferredPlayer = "Cancella player preferito",
        myList = "La mia lista", clearMyList = "Svuota La mia lista",
        addToMyList = "Aggiungi a La mia lista", removeFromMyList = "Rimuovi da La mia lista",
        myListEmpty = "La mia lista è vuota.",
        recentSearches = "Ricerche recenti", clearSearchHistory = "Cancella cronologia ricerche",
        copyMagnetLink = "Copia link magnet", magnetLinkCopied = "Link magnet copiato",
        sortQuality = "Qualità", sortDate = "Data",
        peers = "Leecher", uploadedOn = "Caricato",
        torrentRowDescription = "%1\$s. Qualità %2\$s. %3\$s. %4\$d seed. %5\$d leecher.",
        noResultsForFilter = "Nessun risultato corrisponde ai filtri attivi.",
    ) },

    "ES" to lazy { AppStrings(
        yes = "Sí", no = "No", back = "Atrás", save = "Guardar",
        refresh = "Actualizar", cancel = "Cancelar", confirm = "Confirmar",
        exitTitle = "¿Salir?", exitMessage = "¿Quieres cerrar la aplicación?",
        updateTitle = "Actualización Disponible",
        updateMessage = "Hay una nueva versión disponible. ¿Quieres descargarla?",
        aboutTitle = "Acerca de la App",
        aboutText = "MovieTorrentSearchTV v${io.github.flavyu22.movietorrentsearchtv.util.Constants.APP_VERSION}\nBuscar Películas y Series.\nOptimizado para Android TV.",
        logoutConfirm = "¿Estás seguro de que quieres cerrar sesión?",
        movies = "Películas", series = "Series",
        changeLanguage = "Cambiar Idioma", update = "Actualizar",
        checkingUpdates = "Buscando actualizaciones...", about = "Acerca de",
        trailer = "Trailer",
        logout = "Cerrar sesión",
        history = "Historial", clearHistory = "Limpiar Historial",
        torrserverSettings = "Ajustes de Torrserver", scanNetwork = "Escanear Red",
        movieLabel = "PELÍCULA", seriesLabel = "SERIE",
        availableServers = "Servidores disponibles (%d):",
        torrserverInfo = "Torrserver puede ser local (127.0.0.1:8090) o un servidor en línea.",
        genres = "GÉNEROS", years = "AÑOS", quality = "CALIDAD", rating = "VOTO",
        sortBy = "ORDENAR", sortSeeds = "Seeds", sortSize = "Tamaño", sortSource = "Fuente",
        searchPlaceholder = "Buscar...",
        prev = "Anterior", next = "Siguiente", page = "Página",
        magnetSources = "Fuentes Magnet:", 
        otherSources = "Otras Fuentes (Web):",
        noSources = "No se han encontrado fuentes.",
        multiSourceResults = "▼ Resultados Multi-Fuente",
        processingTorrserver = "Procesando en Torrserver...",
        searchingMultiple = "Buscando en múltiples fuentes...",
        playWith = "Reproducir con:",
        installBitTorrent = "Instala un cliente BitTorrent (ej. nPlayer).",
        installPlayer = "Instala un reproductor de video.",
        resultsSummary = "%d resultados (%dms)",
        torrserverConnected = "Torrserver: %s",
        loginTitle = "Iniciar sesión", username = "Usuario",
        password = "Contraseña", login = "Entrar",
        loginError = "¡Usuario o contraseña inválidos!",
        loginEmptyFields = "Por favor, complete todos los campos",
        contactCredentials = "Acceso local protegido en este dispositivo",
        playerError = "Error del reproductor: %s", torrserverError = "Torrserver: %s",
        voiceLang = "es-ES", langName = "Español",
        developer = "Desarrollador: OxigenForFlower",
        authSetupTitle = "Configurar el acceso local",
        authSetupMessage = "Crea un perfil local y un PIN o una frase de contraseña. Los datos nunca salen de este dispositivo.",
        authUnlockMessage = "Desbloquea el perfil local en este dispositivo.",
        authSetupAction = "Crear y continuar",
        authLockedMessage = "Demasiados intentos. Inténtalo de nuevo en %d segundos.",
        authCredentialHint = "Usa al menos 6 caracteres.",
        authConfirmCredential = "Confirma el PIN o la frase de contraseña",
        authCredentialMismatch = "Las credenciales no coinciden.",
        authResetAction = "Restablecer el acceso local",
        authResetConfirm = "Los datos de acceso local están dañados. ¿Quieres restablecerlos y crear una credencial nueva?",
        magnetConfirmTitle = "¿Abrir el enlace magnet?",
        magnetConfirmMessage = "Otra aplicación ha solicitado reproducir un torrent. Continúa solo si confías en la fuente.",
        retry = "Reintentar", allFilter = "Todos", loading = "Cargando…", genericMovie = "Película", close = "Cerrar",
        menu = "Menú", voiceSearch = "Búsqueda por voz",
        actionUnavailableTitle = "Acción no disponible",
        voiceSearchUnavailable = "La búsqueda por voz no está disponible en este dispositivo.",
        trailerUnavailable = "Ninguna aplicación compatible puede abrir el tráiler.",
        openSourcePage = "Abrir página de la fuente", playTorrent = "Reproducir torrent",
        browserContentDescription = "Página web de la fuente. Usa el mando para mover el puntero y pulsa Seleccionar para activar un enlace.",
        configuredServer = "Servidor configurado", disableTorrserver = "Desactivar Torrserver", scanning = "Buscando…",
        manualAddressHint = "192.168.1.10:8090 o https://servidor.example",
        noServersFound = "No se encontró ningún servidor. Selecciona “Escanear red” para volver a buscar.",
        selected = "Seleccionado", connectionSucceeded = "Conectado a %s (%d ms)",
        connectionFailed = "No se pudo conectar con %s.",
        invalidServerAddress = "Introduce una dirección Torrserver válida.",
        serverScanFailed = "El escaneo de red falló. Inténtalo de nuevo.",
        serverUnreachable = "No se puede acceder al Torrserver.",
        catalogueNetworkIssue = "No se pudo cargar el catálogo. Comprueba la red e inténtalo de nuevo.",
        tmdbNotConfigured = "TMDB no está configurado. El catálogo de series muestra estrenos recientes de los proveedores de torrents, sin pósters ni valoraciones.",
        partialResults = "Algunas fuentes del catálogo no están disponibles. Se muestran los resultados disponibles.",
        updateOperationFailed = "La operación de actualización falló. Inténtalo de nuevo más tarde.",
        torrentResultDescription = "%s, %s, %s, %d semillas",
        clearPreferredPlayer = "Borrar reproductor preferido",
        myList = "Mi lista", clearMyList = "Vaciar Mi lista",
        addToMyList = "Añadir a Mi lista", removeFromMyList = "Quitar de Mi lista",
        myListEmpty = "Mi lista está vacía.",
        recentSearches = "Búsquedas recientes", clearSearchHistory = "Borrar historial de búsqueda",
        copyMagnetLink = "Copiar enlace magnet", magnetLinkCopied = "Enlace magnet copiado",
        sortQuality = "Calidad", sortDate = "Fecha",
        peers = "Leechers", uploadedOn = "Subido",
        torrentRowDescription = "%1\$s. Calidad %2\$s. %3\$s. %4\$d semillas. %5\$d leechers.",
        noResultsForFilter = "Ningún resultado coincide con los filtros activos.",
    ) },

    "FR" to lazy { AppStrings(
        yes = "Oui", no = "Non", back = "Retour", save = "Enregistrer",
        refresh = "Actualiser", cancel = "Annuler", confirm = "Confirmer",
        exitTitle = "Quitter ?", exitMessage = "Voulez-vous fermer l'application ?",
        updateTitle = "Mise à jour Disponible",
        updateMessage = "Une nouvelle version est disponible. Voulez-vous la télécharger ?",
        aboutTitle = "À propos de l'App",
        aboutText = "MovieTorrentSearchTV v${io.github.flavyu22.movietorrentsearchtv.util.Constants.APP_VERSION}\nRecherche de Films et Séries.\nOptimisé pour Android TV.",
        logoutConfirm = "Êtes-vous sûr de vouloir vous déconnecter ?",
        movies = "Films", series = "Séries",
        changeLanguage = "Changer de Langue", update = "Mise à jour",
        checkingUpdates = "Vérification des mises à jour...", about = "À propos",
        trailer = "Bande-annonce",
        logout = "Déconnexion",
        history = "Historique", clearHistory = "Effacer l'Historique",
        torrserverSettings = "Paramètres Torrserver", scanNetwork = "Scanner le Réseau",
        movieLabel = "FILM", seriesLabel = "SÉRIE",
        availableServers = "Serveurs disponibles (%d):",
        torrserverInfo = "Torrserver peut être local (127.0.0.1:8090) ou un serveur en ligne.",
        genres = "GENRES", years = "ANNÉES", quality = "QUALITÉ", rating = "NOTE",
        sortBy = "TRIER", sortSeeds = "Seeds", sortSize = "Taille", sortSource = "Source",
        searchPlaceholder = "Rechercher...",
        prev = "Préc.", next = "Suiv.", page = "Page",
        magnetSources = "Sources Magnet :", 
        otherSources = "Autres Sources (Web) :",
        noSources = "Aucune source trouvée.",
        multiSourceResults = "▼ Résultats Multi-Sources",
        processingTorrserver = "Traitement dans Torrserver...",
        searchingMultiple = "Recherche dans plusieurs sources...",
        playWith = "Lire avec :",
        installBitTorrent = "Installez un client BitTorrent (ex. nPlayer).",
        installPlayer = "Installez un lecteur vidéo.",
        resultsSummary = "%d résultats (%dms)",
        torrserverConnected = "Torrserver: %s",
        loginTitle = "Connexion", username = "Utilisateur",
        password = "Mot de passe", login = "Se connecter",
        loginError = "Utilisateur ou mot de passe invalide !",
        loginEmptyFields = "Veuillez remplir tous les champs",
        contactCredentials = "Accès local protégé sur cet appareil",
        playerError = "Erreur lecteur : %s", torrserverError = "Torrserver : %s",
        voiceLang = "fr-FR", langName = "Français",
        developer = "Développeur : OxigenForFlower",
        authSetupTitle = "Configurer l’accès local",
        authSetupMessage = "Créez un profil local et un code PIN ou une phrase secrète. Ces données ne quittent jamais cet appareil.",
        authUnlockMessage = "Déverrouillez le profil local sur cet appareil.",
        authSetupAction = "Créer et continuer",
        authLockedMessage = "Trop de tentatives. Réessayez dans %d secondes.",
        authCredentialHint = "Utilisez au moins 6 caractères.",
        authConfirmCredential = "Confirmez le code PIN ou la phrase secrète",
        authCredentialMismatch = "Les identifiants ne correspondent pas.",
        authResetAction = "Réinitialiser l’accès local",
        authResetConfirm = "Les données d’accès locales sont endommagées. Voulez-vous les réinitialiser et créer un nouvel identifiant ?",
        magnetConfirmTitle = "Ouvrir le lien magnet ?",
        magnetConfirmMessage = "Une autre application a demandé la lecture d’un torrent. Continuez uniquement si vous faites confiance à la source.",
        retry = "Réessayer", allFilter = "Tous", loading = "Chargement…", genericMovie = "Film", close = "Fermer",
        menu = "Menu", voiceSearch = "Recherche vocale",
        actionUnavailableTitle = "Action indisponible",
        voiceSearchUnavailable = "La recherche vocale n’est pas disponible sur cet appareil.",
        trailerUnavailable = "Aucune application compatible ne peut ouvrir cette bande-annonce.",
        openSourcePage = "Ouvrir la page source", playTorrent = "Lire le torrent",
        browserContentDescription = "Page web de la source. Utilisez la télécommande pour déplacer le pointeur et appuyez sur Sélectionner pour activer un lien.",
        configuredServer = "Serveur configuré", disableTorrserver = "Désactiver Torrserver", scanning = "Recherche…",
        manualAddressHint = "192.168.1.10:8090 ou https://serveur.example",
        noServersFound = "Aucun serveur trouvé. Sélectionnez « Scanner le réseau » pour relancer la recherche.",
        selected = "Sélectionné", connectionSucceeded = "Connecté à %s (%d ms)",
        connectionFailed = "Connexion à %s impossible.",
        invalidServerAddress = "Saisissez une adresse Torrserver valide.",
        serverScanFailed = "Le scan du réseau a échoué. Réessayez.",
        serverUnreachable = "Le Torrserver est inaccessible.",
        catalogueNetworkIssue = "Le catalogue n’a pas pu être chargé. Vérifiez le réseau et réessayez.",
        tmdbNotConfigured = "TMDB n’est pas configuré. Le catalogue des séries affiche les sorties récentes des fournisseurs de torrents, sans affiches ni notes.",
        partialResults = "Certaines sources du catalogue sont indisponibles. Les résultats accessibles sont affichés.",
        updateOperationFailed = "L’opération de mise à jour a échoué. Réessayez plus tard.",
        torrentResultDescription = "%s, %s, %s, %d seeders",
        clearPreferredPlayer = "Effacer le lecteur préféré",
        myList = "Ma liste", clearMyList = "Vider Ma liste",
        addToMyList = "Ajouter à Ma liste", removeFromMyList = "Retirer de Ma liste",
        myListEmpty = "Ma liste est vide.",
        recentSearches = "Recherches récentes", clearSearchHistory = "Effacer l'historique de recherche",
        copyMagnetLink = "Copier le lien magnet", magnetLinkCopied = "Lien magnet copié",
        sortQuality = "Qualité", sortDate = "Date",
        peers = "Leechers", uploadedOn = "Ajouté",
        torrentRowDescription = "%1\$s. Qualité %2\$s. %3\$s. %4\$d seeds. %5\$d leechers.",
        noResultsForFilter = "Aucun résultat ne correspond aux filtres actifs.",
    ) },

    "DE" to lazy { AppStrings(
        yes = "Ja", no = "Nein", back = "Zurück", save = "Speichern",
        refresh = "Aktualisieren", cancel = "Abbrechen", confirm = "Bestätigen",
        exitTitle = "Beenden?", exitMessage = "Möchten Sie die App schließen?",
        updateTitle = "Update Verfügbar",
        updateMessage = "Eine neue Version ist verfügbar. Möchten Sie sie herunterladen?",
        aboutTitle = "Über die App",
        aboutText = "MovieTorrentSearchTV v${io.github.flavyu22.movietorrentsearchtv.util.Constants.APP_VERSION}\nSuche nach Filmen und Serien.\nOptimiert für Android TV.",
        logoutConfirm = "Sind Sie sicher, dass Sie sich abmelden möchten?",
        movies = "Filme", series = "Serien",
        changeLanguage = "Sprache Ändern", update = "Update",
        checkingUpdates = "Suche nach Updates...", about = "Über",
        trailer = "Trailer",
        logout = "Abmelden",
        history = "Verlauf", clearHistory = "Verlauf löschen",
        torrserverSettings = "Torrserver-Einstellungen", scanNetwork = "Netzwerk Scannen",
        movieLabel = "FILM", seriesLabel = "SERIE",
        availableServers = "Verfügbare Server (%d):",
        torrserverInfo = "Torrserver kann lokal (127.0.0.1:8090) oder ein Online-Server sein.",
        genres = "GENRES", years = "JAHRE", quality = "QUALITÄT", rating = "VOTUM",
        sortBy = "SORTIEREN", sortSeeds = "Seeds", sortSize = "Größe", sortSource = "Quelle",
        searchPlaceholder = "Suchen...",
        prev = "Zurück", next = "Weiter", page = "Seite",
        magnetSources = "Magnet-Quellen:", 
        otherSources = "Andere Quellen (Web):",
        noSources = "Keine Quellen gefunden.",
        multiSourceResults = "▼ Multi-Quellen-Ergebnisse",
        processingTorrserver = "Verarbeitung in Torrserver...",
        searchingMultiple = "Suche in mehreren Quellen...",
        playWith = "Abspielen mit:",
        installBitTorrent = "Installieren Sie einen BitTorrent-Client (z. B. nPlayer).",
        installPlayer = "Installieren Sie einen Videoplayer.",
        resultsSummary = "%d Ergebnisse (%dms)",
        torrserverConnected = "Torrserver: %s",
        loginTitle = "Anmelden", username = "Benutzername",
        password = "Passwort", login = "Anmelden",
        loginError = "Ungültiger Benutzername oder Passwort!",
        loginEmptyFields = "Bitte füllen Sie alle Felder aus",
        contactCredentials = "Lokaler Zugriff auf diesem Gerät geschützt",
        playerError = "Player-Fehler: %s", torrserverError = "Torrserver: %s",
        voiceLang = "de-DE", langName = "Deutsch",
        developer = "Entwickler: OxigenForFlower",
        authSetupTitle = "Lokalen Zugriff einrichten",
        authSetupMessage = "Erstellen Sie ein lokales Profil und eine PIN oder Passphrase. Diese Daten verlassen das Gerät nicht.",
        authUnlockMessage = "Entsperren Sie das lokale Profil auf diesem Gerät.",
        authSetupAction = "Erstellen und fortfahren",
        authLockedMessage = "Zu viele Versuche. Versuchen Sie es in %d Sekunden erneut.",
        authCredentialHint = "Verwenden Sie mindestens 6 Zeichen.",
        authConfirmCredential = "PIN oder Passphrase bestätigen",
        authCredentialMismatch = "Die Zugangsdaten stimmen nicht überein.",
        authResetAction = "Lokalen Zugriff zurücksetzen",
        authResetConfirm = "Die lokalen Zugangsdaten sind beschädigt. Möchten Sie sie zurücksetzen und neue Zugangsdaten erstellen?",
        magnetConfirmTitle = "Magnet-Link öffnen?",
        magnetConfirmMessage = "Eine andere App hat die Wiedergabe eines Torrents angefordert. Fahren Sie nur fort, wenn Sie der Quelle vertrauen.",
        retry = "Erneut versuchen", allFilter = "Alle", loading = "Wird geladen…", genericMovie = "Film", close = "Schließen",
        menu = "Menü", voiceSearch = "Sprachsuche",
        actionUnavailableTitle = "Aktion nicht verfügbar",
        voiceSearchUnavailable = "Die Sprachsuche ist auf diesem Gerät nicht verfügbar.",
        trailerUnavailable = "Keine kompatible App kann diesen Trailer öffnen.",
        openSourcePage = "Quellseite öffnen", playTorrent = "Torrent abspielen",
        browserContentDescription = "Webseite der Quelle. Bewegen Sie den Zeiger mit dem Steuerkreuz und drücken Sie Auswählen, um einen Link zu öffnen.",
        configuredServer = "Konfigurierter Server", disableTorrserver = "Torrserver deaktivieren", scanning = "Suche läuft…",
        manualAddressHint = "192.168.1.10:8090 oder https://server.example",
        noServersFound = "Kein Server gefunden. Wählen Sie „Netzwerk scannen“, um erneut zu suchen.",
        selected = "Ausgewählt", connectionSucceeded = "Mit %s verbunden (%d ms)",
        connectionFailed = "Verbindung mit %s fehlgeschlagen.",
        invalidServerAddress = "Geben Sie eine gültige Torrserver-Adresse ein.",
        serverScanFailed = "Der Netzwerkscan ist fehlgeschlagen. Versuchen Sie es erneut.",
        serverUnreachable = "Der Torrserver ist nicht erreichbar.",
        catalogueNetworkIssue = "Der Katalog konnte nicht geladen werden. Prüfen Sie das Netzwerk und versuchen Sie es erneut.",
        tmdbNotConfigured = "TMDB ist nicht konfiguriert. Der Serienkatalog zeigt aktuelle Veröffentlichungen der Torrent-Anbieter, ohne Poster oder Bewertungen.",
        partialResults = "Einige Katalogquellen sind nicht verfügbar. Die verfügbaren Ergebnisse werden angezeigt.",
        updateOperationFailed = "Die Aktualisierung ist fehlgeschlagen. Versuchen Sie es später erneut.",
        torrentResultDescription = "%s, %s, %s, %d Seeds",
        clearPreferredPlayer = "Bevorzugten Player löschen",
        myList = "Meine Liste", clearMyList = "Meine Liste leeren",
        addToMyList = "Zu Meine Liste hinzufügen", removeFromMyList = "Aus Meine Liste entfernen",
        myListEmpty = "Meine Liste ist leer.",
        recentSearches = "Letzte Suchen", clearSearchHistory = "Suchverlauf löschen",
        copyMagnetLink = "Magnet-Link kopieren", magnetLinkCopied = "Magnet-Link kopiert",
        sortQuality = "Qualität", sortDate = "Datum",
        peers = "Leechers", uploadedOn = "Hochgeladen",
        torrentRowDescription = "%1\$s. Qualität %2\$s. %3\$s. %4\$d Seeder. %5\$d Leecher.",
        noResultsForFilter = "Keine Ergebnisse entsprechen den aktiven Filtern.",
    ) },

    "PT" to lazy { AppStrings(
        yes = "Sim", no = "Não", back = "Voltar", save = "Salvar",
        refresh = "Atualizar", cancel = "Cancelar", confirm = "Confirmar",
        exitTitle = "Sair?", exitMessage = "Deseja fechar o aplicativo?",
        updateTitle = "Atualização Disponível",
        updateMessage = "Uma nova versão está disponível. Deseja transferi-la?",
        aboutTitle = "Sobre o App",
        aboutText = "MovieTorrentSearchTV v${io.github.flavyu22.movietorrentsearchtv.util.Constants.APP_VERSION}\nBusca de Filmes e Séries.\nOtimizado para Android TV.",
        logoutConfirm = "Tem certeza de que deseja sair?",
        movies = "Filmes", series = "Séries",
        changeLanguage = "Mudar Idioma", update = "Atualizar",
        checkingUpdates = "Verificando atualizações...", about = "Sobre",
        trailer = "Trailer",
        logout = "Sair",
        history = "Histórico", clearHistory = "Limpar Histórico",
        torrserverSettings = "Configurações do Torrserver", scanNetwork = "Escanear Rede",
        movieLabel = "FILME", seriesLabel = "SÉRIE",
        availableServers = "Servidores disponíveis (%d):",
        torrserverInfo = "O Torrserver pode ser local (127.0.0.1:8090) ou um servidor online.",
        genres = "GÊNEROS", years = "ANOS", quality = "QUALIDADE", rating = "VOTO",
        sortBy = "ORDENAR", sortSeeds = "Seeds", sortSize = "Tamanho", sortSource = "Fonte",
        searchPlaceholder = "Buscar...",
        prev = "Anterior", next = "Próximo", page = "Página",
        magnetSources = "Fontes Magnet:", 
        otherSources = "Outras Fontes (Web):",
        noSources = "Nenhuma fonte encontrada.",
        multiSourceResults = "▼ Resultados Multi-Fonte",
        processingTorrserver = "Processando no Torrserver...",
        searchingMultiple = "Buscando em múltiplas fontes...",
        playWith = "Reproduzir com:",
        installBitTorrent = "Instale um cliente BitTorrent (ex. nPlayer).",
        installPlayer = "Instale um player de vídeo.",
        resultsSummary = "%d resultados (%dms)",
        torrserverConnected = "Torrserver: %s",
        loginTitle = "Entrar", username = "Usuário",
        password = "Senha", login = "Entrar",
        loginError = "Utilizador ou senha inválidos!",
        loginEmptyFields = "Por favor, preencha todos os campos",
        contactCredentials = "Acesso local protegido neste dispositivo",
        playerError = "Erro no player: %s", torrserverError = "Torrserver: %s",
        voiceLang = "pt-PT", langName = "Português",
        developer = "Desenvolvedor: OxigenForFlower",
        authSetupTitle = "Configurar o acesso local",
        authSetupMessage = "Crie um perfil local e um PIN ou uma frase-passe. Estes dados nunca saem deste dispositivo.",
        authUnlockMessage = "Desbloqueie o perfil local neste dispositivo.",
        authSetupAction = "Criar e continuar",
        authLockedMessage = "Demasiadas tentativas. Tente novamente dentro de %d segundos.",
        authCredentialHint = "Utilize pelo menos 6 caracteres.",
        authConfirmCredential = "Confirme o PIN ou a frase-passe",
        authCredentialMismatch = "As credenciais não coincidem.",
        authResetAction = "Repor o acesso local",
        authResetConfirm = "Os dados de acesso local estão danificados. Pretende repô-los e criar uma nova credencial?",
        magnetConfirmTitle = "Abrir ligação magnet?",
        magnetConfirmMessage = "Outra aplicação solicitou a reprodução de um torrent. Continue apenas se confiar na fonte.",
        retry = "Tentar novamente", allFilter = "Todos", loading = "A carregar…", genericMovie = "Filme", close = "Fechar",
        menu = "Menu", voiceSearch = "Pesquisa por voz",
        actionUnavailableTitle = "Ação indisponível",
        voiceSearchUnavailable = "A pesquisa por voz não está disponível neste dispositivo.",
        trailerUnavailable = "Nenhuma aplicação compatível consegue abrir este trailer.",
        openSourcePage = "Abrir página da fonte", playTorrent = "Reproduzir torrent",
        browserContentDescription = "Página Web da fonte. Use o comando para mover o ponteiro e prima Selecionar para ativar uma ligação.",
        configuredServer = "Servidor configurado", disableTorrserver = "Desativar Torrserver", scanning = "A procurar…",
        manualAddressHint = "192.168.1.10:8090 ou https://servidor.example",
        noServersFound = "Nenhum servidor encontrado. Selecione “Escanear rede” para procurar novamente.",
        selected = "Selecionado", connectionSucceeded = "Ligado a %s (%d ms)",
        connectionFailed = "Não foi possível ligar a %s.",
        invalidServerAddress = "Introduza um endereço Torrserver válido.",
        serverScanFailed = "A pesquisa de rede falhou. Tente novamente.",
        serverUnreachable = "Não é possível contactar o Torrserver.",
        catalogueNetworkIssue = "Não foi possível carregar o catálogo. Verifique a rede e tente novamente.",
        tmdbNotConfigured = "O TMDB não está configurado. O catálogo de séries mostra lançamentos recentes dos fornecedores de torrents, sem pôsteres ou classificações.",
        partialResults = "Algumas fontes do catálogo não estão disponíveis. São apresentados os resultados disponíveis.",
        updateOperationFailed = "A operação de atualização falhou. Tente novamente mais tarde.",
        torrentResultDescription = "%s, %s, %s, %d seeds",
        clearPreferredPlayer = "Limpar player preferido",
        myList = "A minha lista", clearMyList = "Limpar A minha lista",
        addToMyList = "Adicionar à A minha lista", removeFromMyList = "Remover de A minha lista",
        myListEmpty = "A minha lista está vazia.",
        recentSearches = "Pesquisas recentes", clearSearchHistory = "Limpar histórico de pesquisa",
        copyMagnetLink = "Copiar link magnet", magnetLinkCopied = "Link magnet copiado",
        sortQuality = "Qualidade", sortDate = "Data",
        peers = "Leechers", uploadedOn = "Enviado",
        torrentRowDescription = "%1\$s. Qualidade %2\$s. %3\$s. %4\$d seeds. %5\$d leechers.",
        noResultsForFilter = "Nenhum resultado corresponde aos filtros ativos.",
    ) },

    "RU" to lazy { AppStrings(
        yes = "Да", no = "Нет", back = "Назад", save = "Сохранить",
        refresh = "Обновить", cancel = "Отмена", confirm = "Подтвердить",
        exitTitle = "Выйти?", exitMessage = "Закрыть приложение?",
        updateTitle = "Доступно обновление",
        updateMessage = "Доступна новая версия. Хотите скачать?",
        aboutTitle = "О приложении",
        aboutText = "MovieTorrentSearchTV v${io.github.flavyu22.movietorrentsearchtv.util.Constants.APP_VERSION}\nПоиск фильмов и сериалов.\nОптимизировано для Android TV.",
        logoutConfirm = "Вы уверены, что хотите выйти?",
        movies = "Фильмы", series = "Сериалы",
        changeLanguage = "Сменить язык", update = "Обновить",
        checkingUpdates = "Поиск обновлений...", about = "О программе",
        trailer = "Трейлер",
        logout = "Выйти",
        history = "История", clearHistory = "Очистить историю",
        torrserverSettings = "Настройки Torrserver", scanNetwork = "Сканировать сеть",
        movieLabel = "ФИЛЬМ", seriesLabel = "СЕРИАЛ",
        availableServers = "Доступные серверы (%d):",
        torrserverInfo = "Torrserver может быть локальным (127.0.0.1:8090) или онлайн-сервером.",
        genres = "ЖАНРЫ", years = "ГОДЫ", quality = "КАЧЕСТВО", rating = "РЕЙТИНГ",
        sortBy = "СОРТИРОВАТЬ", sortSeeds = "Сиды", sortSize = "Размер", sortSource = "Источник",
        searchPlaceholder = "Поиск...",
        prev = "Пред.", next = "След.", page = "Страница",
        magnetSources = "Magnet-источники:", 
        otherSources = "Другие источники (Web):",
        noSources = "Источники не найдены.",
        multiSourceResults = "▼ Результаты из разных источников",
        processingTorrserver = "Обработка в Torrserver...",
        searchingMultiple = "Поиск по нескольким источникам...",
        playWith = "Играть с:",
        installBitTorrent = "Установите BitTorrent-клиент (например, nPlayer).",
        installPlayer = "Установите видеоплеер.",
        resultsSummary = "%d результатов (%d мс)",
        torrserverConnected = "Torrserver: %s",
        loginTitle = "Вход", username = "Имя пользователя",
        password = "Пароль", login = "Войти",
        loginError = "Неверное имя пользователя или пароль!",
        loginEmptyFields = "Пожалуйста, заполните все поля",
        contactCredentials = "Локальный доступ защищён на этом устройстве",
        playerError = "Ошибка плеера: %s", torrserverError = "Torrserver: %s",
        voiceLang = "ru-RU", langName = "Русский",
        developer = "Разработчик: OxigenForFlower",
        authSetupTitle = "Настроить локальный доступ",
        authSetupMessage = "Создайте локальный профиль и PIN-код или парольную фразу. Эти данные не покидают устройство.",
        authUnlockMessage = "Разблокируйте локальный профиль на этом устройстве.",
        authSetupAction = "Создать и продолжить",
        authLockedMessage = "Слишком много попыток. Повторите через %d секунд.",
        authCredentialHint = "Используйте не менее 6 символов.",
        authConfirmCredential = "Подтвердите PIN-код или парольную фразу",
        authCredentialMismatch = "Учётные данные не совпадают.",
        authResetAction = "Сбросить локальный доступ",
        authResetConfirm = "Локальные данные доступа повреждены. Сбросить их и создать новые учётные данные?",
        magnetConfirmTitle = "Открыть magnet-ссылку?",
        magnetConfirmMessage = "Другое приложение запросило воспроизведение торрента. Продолжайте, только если доверяете источнику.",
        retry = "Повторить", allFilter = "Все", loading = "Загрузка…", genericMovie = "Фильм", close = "Закрыть",
        menu = "Меню", voiceSearch = "Голосовой поиск",
        actionUnavailableTitle = "Действие недоступно",
        voiceSearchUnavailable = "Голосовой поиск недоступен на этом устройстве.",
        trailerUnavailable = "Нет совместимого приложения для открытия трейлера.",
        openSourcePage = "Открыть страницу источника", playTorrent = "Воспроизвести торрент",
        browserContentDescription = "Веб-страница источника. Перемещайте указатель кнопками навигации и нажмите Выбор, чтобы открыть ссылку.",
        configuredServer = "Настроенный сервер", disableTorrserver = "Отключить Torrserver", scanning = "Поиск…",
        manualAddressHint = "192.168.1.10:8090 или https://server.example",
        noServersFound = "Серверы не найдены. Выберите «Сканировать сеть», чтобы повторить поиск.",
        selected = "Выбрано", connectionSucceeded = "Подключено к %s (%d мс)",
        connectionFailed = "Не удалось подключиться к %s.",
        invalidServerAddress = "Введите корректный адрес Torrserver.",
        serverScanFailed = "Не удалось просканировать сеть. Повторите попытку.",
        serverUnreachable = "Torrserver недоступен.",
        catalogueNetworkIssue = "Не удалось загрузить каталог. Проверьте сеть и повторите попытку.",
        tmdbNotConfigured = "TMDB не настроен. Каталог сериалов показывает недавние релизы от торрент-провайдеров, без постеров и оценок.",
        partialResults = "Некоторые источники каталога недоступны. Показаны доступные результаты.",
        updateOperationFailed = "Не удалось выполнить обновление. Повторите попытку позже.",
        torrentResultDescription = "%s, %s, %s, сиды: %d",
        clearPreferredPlayer = "Очистить выбранный плеер",
        myList = "Мой список", clearMyList = "Очистить мой список",
        addToMyList = "Добавить в мой список", removeFromMyList = "Удалить из моего списка",
        myListEmpty = "Мой список пуст.",
        recentSearches = "Недавние запросы", clearSearchHistory = "Очистить историю поиска",
        copyMagnetLink = "Копировать magnet-ссылку", magnetLinkCopied = "Magnet-ссылка скопирована",
        sortQuality = "Качество", sortDate = "Дата",
        peers = "Личеры", uploadedOn = "Добавлено",
        torrentRowDescription = "%1\$s. Качество %2\$s. %3\$s. %4\$d сидов. %5\$d личеров.",
        noResultsForFilter = "Нет результатов, подходящих под активные фильтры.",
    ) },

    "EL" to lazy { AppStrings(
        yes = "Ναι", no = "Όχι", back = "Πίσω", save = "Αποθήκευση",
        refresh = "Ανανέωση", cancel = "Ακύρωση", confirm = "Επιβεβαίωση",
        exitTitle = "Έξοδος;", exitMessage = "Θέλετε να κλείσετε την εφαρμογή;",
        updateTitle = "Διαθέσιμη Ενημέρωση",
        updateMessage = "Μια νέα έκδοση είναι διαθέσιμη. Θέλετε να την κατεβάσετε;",
        aboutTitle = "Σχετικά με την Εφαρμογή",
        aboutText = "MovieTorrentSearchTV v${io.github.flavyu22.movietorrentsearchtv.util.Constants.APP_VERSION}\nΑναζήτηση Ταινιών και Σειρών.\nΒελτιστοποιημένο για Android TV.",
        logoutConfirm = "Είστε βέβαιοι ότι θέλετε να αποσυνδεθείτε;",
        movies = "Ταινίες", series = "Σειρές",
        changeLanguage = "Αλλαγή Γλώσσας", update = "Ενημέρωση",
        checkingUpdates = "Έλεγχος για ενημερώσεις...", about = "Σχετικά",
        trailer = "Trailer",
        logout = "Αποσύνδεση",
        history = "Ιστορικό", clearHistory = "Καθαρισμός Ιστορικού",
        torrserverSettings = "Ρυθμίσεις Torrserver", scanNetwork = "Σάρωση Δικτύου",
        movieLabel = "ΤΑΙΝΙΑ", seriesLabel = "ΣΕΙΡΑ",
        availableServers = "Διαθέσιμοι διακομιστές (%d):",
        torrserverInfo = "Το Torrserver μπορεί να είναι τοπικό (127.0.0.1:8090) ή online διακομιστής.",
        genres = "ΚΑΤΗΓΟΡΙΕΣ", years = "ΕΤΗ", quality = "ΠΟΙΟΤΗΤΑ", rating = "ΒΑΘΜΟΛΟΓΙΑ",
        sortBy = "ΤΑΞΙΝΟΜΗΣΗ", sortSeeds = "Seeds", sortSize = "Μέγεθος", sortSource = "Πηγή",
        searchPlaceholder = "Αναζήτηση...",
        prev = "Προηγ.", next = "Επόμ.", page = "Σελίδα",
        magnetSources = "Πηγές Magnet:", 
        otherSources = "Άλλες Πηγές (Web):",
        noSources = "Δεν βρέθηκαν πηγές.",
        multiSourceResults = "▼ Αποτελέσματα Πολλαπλών Πηγών",
        processingTorrserver = "Επεξεργασία στο Torrserver...",
        searchingMultiple = "Αναζήτηση σε πολλαπλές πηγές...",
        playWith = "Αναπαραγωγή με:",
        installBitTorrent = "Εγκαταστήστε έναν BitTorrent client (π.χ. nPlayer).",
        installPlayer = "Εγκαταστήστε ένα πρόγραμμα αναπαραγωγής βίντεο.",
        resultsSummary = "%d αποτελέσματα (%dms)",
        torrserverConnected = "Τοrrserver: %s",
        loginTitle = "Σύνδεση", username = "Όνομα χρήστη",
        password = "Κωδικός", login = "Είσοδος",
        loginError = "Μη έγκυρο όνομα χρήστη ή κωδικός!",
        loginEmptyFields = "Παρακαλώ συμπληρώστε όλα τα πεδία",
        contactCredentials = "Προστατευμένη τοπική πρόσβαση σε αυτή τη συσκευή",
        playerError = "Σφάλμα προγράμματος αναπαραγωγής: %s", torrserverError = "Torrserver: %s",
        voiceLang = "el-GR", langName = "Ελληνικά",
        developer = "Δημιουργός: OxigenForFlower",
        authSetupTitle = "Ρύθμιση τοπικής πρόσβασης",
        authSetupMessage = "Δημιουργήστε ένα τοπικό προφίλ και PIN ή φράση πρόσβασης. Τα δεδομένα δεν εγκαταλείπουν ποτέ αυτή τη συσκευή.",
        authUnlockMessage = "Ξεκλειδώστε το τοπικό προφίλ σε αυτή τη συσκευή.",
        authSetupAction = "Δημιουργία και συνέχεια",
        authLockedMessage = "Πάρα πολλές προσπάθειες. Δοκιμάστε ξανά σε %d δευτερόλεπτα.",
        authCredentialHint = "Χρησιμοποιήστε τουλάχιστον 6 χαρακτήρες.",
        authConfirmCredential = "Επιβεβαιώστε το PIN ή τη φράση πρόσβασης",
        authCredentialMismatch = "Τα στοιχεία πρόσβασης δεν ταιριάζουν.",
        authResetAction = "Επαναφορά τοπικής πρόσβασης",
        authResetConfirm = "Τα τοπικά στοιχεία πρόσβασης έχουν καταστραφεί. Να γίνει επαναφορά και δημιουργία νέων στοιχείων;",
        magnetConfirmTitle = "Άνοιγμα συνδέσμου magnet;",
        magnetConfirmMessage = "Μια άλλη εφαρμογή ζήτησε την αναπαραγωγή torrent. Συνεχίστε μόνο αν εμπιστεύεστε την πηγή.",
        retry = "Επανάληψη", allFilter = "Όλα", loading = "Φόρτωση…", genericMovie = "Ταινία", close = "Κλείσιμο",
        menu = "Μενού", voiceSearch = "Φωνητική αναζήτηση",
        actionUnavailableTitle = "Η ενέργεια δεν είναι διαθέσιμη",
        voiceSearchUnavailable = "Η φωνητική αναζήτηση δεν είναι διαθέσιμη σε αυτή τη συσκευή.",
        trailerUnavailable = "Καμία συμβατή εφαρμογή δεν μπορεί να ανοίξει το trailer.",
        openSourcePage = "Άνοιγμα σελίδας πηγής", playTorrent = "Αναπαραγωγή torrent",
        browserContentDescription = "Ιστοσελίδα πηγής. Μετακινήστε τον δείκτη με το τηλεχειριστήριο και πατήστε Επιλογή για να ενεργοποιήσετε έναν σύνδεσμο.",
        configuredServer = "Ρυθμισμένος διακομιστής", disableTorrserver = "Απενεργοποίηση Torrserver", scanning = "Σάρωση…",
        manualAddressHint = "192.168.1.10:8090 ή https://server.example",
        noServersFound = "Δεν βρέθηκε διακομιστής. Επιλέξτε «Σάρωση δικτύου» για νέα αναζήτηση.",
        selected = "Επιλεγμένο", connectionSucceeded = "Σύνδεση με %s (%d ms)",
        connectionFailed = "Η σύνδεση με %s απέτυχε.",
        invalidServerAddress = "Εισαγάγετε έγκυρη διεύθυνση Torrserver.",
        serverScanFailed = "Η σάρωση δικτύου απέτυχε. Δοκιμάστε ξανά.",
        serverUnreachable = "Το Torrserver δεν είναι προσβάσιμο.",
        catalogueNetworkIssue = "Δεν ήταν δυνατή η φόρτωση του καταλόγου. Ελέγξτε το δίκτυο και δοκιμάστε ξανά.",
        tmdbNotConfigured = "Το TMDB δεν έχει ρυθμιστεί. Ο κατάλογος σειρών εμφανίζει πρόσφατες κυκλοφορίες από τους παρόχους torrent, χωρίς αφίσες ή βαθμολογίες.",
        partialResults = "Ορισμένες πηγές καταλόγου δεν είναι διαθέσιμες. Εμφανίζονται τα διαθέσιμα αποτελέσματα.",
        updateOperationFailed = "Η ενημέρωση απέτυχε. Δοκιμάστε ξανά αργότερα.",
        torrentResultDescription = "%s, %s, %s, %d seed",
        clearPreferredPlayer = "Εκκαθάριση προτιμώμενου παίκτη",
        myList = "Η λίστα μου", clearMyList = "Εκκαθάριση λίστας",
        addToMyList = "Προσθήκη στη λίστα μου", removeFromMyList = "Αφαίρεση από τη λίστα μου",
        myListEmpty = "Η λίστα μου είναι κενή.",
        recentSearches = "Πρόσφατες αναζητήσεις", clearSearchHistory = "Εκκαθάριση ιστορικού αναζήτησης",
        copyMagnetLink = "Αντιγραφή συνδέσμου magnet", magnetLinkCopied = "Ο σύνδεσμος magnet αντιγράφηκε",
        sortQuality = "Ποιότητα", sortDate = "Ημερομηνία",
        peers = "Leechers", uploadedOn = "Μεταφορτώθηκε",
        torrentRowDescription = "%1\$s. Ποιότητα %2\$s. %3\$s. %4\$d seeders. %5\$d leechers.",
        noResultsForFilter = "Κανένα αποτέλεσμα δεν ταιριάζει με τα ενεργά φίλτρα.",
    ) },
))
